### ISSUE TITLE
Add a table of contents for AAM series (similar to other tables)

### ISSUE THREAD

**Issue by MadhavBahl** [MadhavBahl/slides#18]
TODO - Create a table similar to the first table in the AAM section and post the link to all 5 playlists 

1. Project 1 - https://www.youtube.com/playlist?list=PLGyA74h_S9NqJvvQ7-l9bUHHS6bMCkgo0
2. Project 2 - https://www.youtube.com/playlist?list=PLGyA74h_S9NppHNrzUSjMQbnuHS9jlAcY
3. Project 3 - https://www.youtube.com/playlist?list=PLGyA74h_S9NrkKnaIrYeOolru4EakosHY
4. Project 4 - https://www.youtube.com/playlist?list=PLGyA74h_S9NrjM7mUiSmpKfUntwEcgMB3
5. Project 5 - https://www.youtube.com/playlist?list=PLGyA74h_S9Nq-rRLG5pqEiaJ87H22S3BW

**Comment by fuadnafiz98** [comment]
Hello @MadhavBahl, Can I work on this issue?

**Comment by MadhavBahl** [comment]
Sure, thanks @fuadnafiz98 ,
Assigned this issue to you

**Comment by fuadnafiz98** [comment]
@MadhavBahl, I have done the changes and created a pull request. Would you please review the changes?
