### ISSUE TITLE
Refactor `dist` and `plugin` to be at the root level of this project

### ISSUE THREAD

**Issue by MadhavBahl** [MadhavBahl/slides#3]
I noticed that dist and plugin folders in the 2nd and 3rd slides were redundant since in both I was using the revealjs library,

both of the folders can be moved out at top level and the links to them can be updated

This should be a good issue for first timers in open source

**Comment by apkolhe** [comment]
@MadhavBahl Can I take this one?

**Comment by MadhavBahlMS** [comment]
Thanks @apkolhe

**Comment by MadhavBahl** [comment]
Thanks @apkolhe

**Comment by apkolhe** [comment]
Thanks @MadhavBahl. I have created a pull request for this change. Could you please review this PR. Cheers!

**Comment by chadrackkyungu** [comment]
Hello Dev it's my first time i want to contributes to this issues but i have got no idea where to start can you please try and explain to me what exactly i can contributes to this issues, so far i know HTML, CSS, JAVASCRIPT please @MadhavBahl  i'm looking forward to contributes

**Comment by MadhavBahl** [comment]
Hey @chadrackkyungu this issue has been already taken up by @apkolhe and is already in PR,
you can check out my other repositories, I have quite a lot of open items in my open source projects,

@chadrackkyungu , you can also check out my videos for more information about open source - 

1. How to find project or issue for your next open source contribution - https://www.youtube.com/watch?v=M37iyGdIJgI
2. The Lean Talks Episode 7: Getting started with Git, GitHub and Open Source - https://www.youtube.com/watch?v=I3AcUV3NZ0A

Hope this would help

**Comment by chadrackkyungu** [comment]
Alright i'm going to check it out, thanks for the feedback 🙏
